
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 5;
  public static final int OPERACION = 13;
  public static final int INT = 18;
  public static final int IGUAL = 15;
  public static final int CC = 9;
  public static final int DIVIDO = 6;
  public static final int ID = 17;
  public static final int POR = 4;
  public static final int CA = 10;
  public static final int PROGRAM = 8;
  public static final int LLC = 12;
  public static final int LLA = 11;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int LET = 16;
  public static final int ENTERO = 14;
  public static final int FIN = 7;
  public static final int MAS = 3;
  public static final int PTCOMA = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "MAS",
  "POR",
  "MENOS",
  "DIVIDO",
  "FIN",
  "PROGRAM",
  "CC",
  "CA",
  "LLA",
  "LLC",
  "OPERACION",
  "ENTERO",
  "IGUAL",
  "LET",
  "ID",
  "INT"
  };
}

